---
- hosts: localhost
  connection: local
  vars:
     vnode_prefix: vnode-
  roles:
    - role: grycap.nfs
      nfs_mode: 'front'
      nfs_exports: [{path: "/home", export: "{{ vnode_prefix }}*.localdomain(rw,async,no_root_squash,no_subtree_check,insecure,crossmnt)"}]
    - role: 'grycap.ssh'
      ssh_type_of_node: 'front'
      ssh_user: horovod
