---
- hosts: localhost
  connection: local
  vars:
    gpu_support: "{{ horovod_gpu_support | default(false) }}"
  roles:
    - role: grycap.nfs
      nfs_mode: 'wn'
      nfs_client_imports: [{ local: "/home", remote: "/home", server_host: "{{ horovod_front_end_ip }}" }]
    - role: 'grycap.ssh'
      ssh_type_of_node: 'wn'
      ssh_user: horovod
    - role: 'grycap.horovod'
