---
- hosts: localhost
  connection: local
  roles:
    - role: grycap.nfs
      nfs_mode: 'wn'
      nfs_client_imports: [{ local: "/home", remote: "/home", server_host: "{{ horovod_front_end_ip }}" }]
    - role: 'grycap.ssh'
      ssh_type_of_node: 'wn'
      ssh_user: horovod
  tasks:
    - name: Install system dependencies in Debian
      apt:
        pkg:
          - python3
          - python3-dev
          - openmpi-bin
          - openmpi-common
          - libopenmpi-dev
          - gcc
          - g++
          - make
          - cmake
          - python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install epel in RedHat
      package:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install system dependencies in RedHat
      package:
        name:
          - python3
          - python3-devel
          - gcc
          - gcc-c++
          - make
          - cmake
          - python3-pip
          - openmpi
          - openmpi-devel
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install python dependencies
      pip:
        name:
          - tensorflow
          - keras
        state: present
        executable: pip3
      environment:
        # This is only needed for RedHat
        PATH: "{{ ansible_env.PATH }}:/usr/lib64/openmpi/bin"

    - name: Install horovod
      pip:
        name: horovod
        state: present
        executable: pip3
        extra_args: --no-binary horovod
      environment:
        HOROVOD_WITH_MPI: 1
        # This is only needed for RedHat
        PATH: "{{ ansible_env.PATH }}:/usr/lib64/openmpi/bin"
