---
- hosts: localhost
  connection: local
  vars:
    server_list: "{{ nomad_server_list | default([ansible_default_ipv4.address]) }}"
    server_private_ip: "{{ IM_NODE_PRIVATE_IP | default(ansible_default_ipv4.address) }}"
    launch_traefik: "{{ nomad_launch_traefik | default(true) }}"
    nomad_input_version: "{{ nomad_version | default('1.7.3') }}"
    consul_input_version: "{{ consul_version | default('1.17.1') }}"
  pre_tasks:
    - name: Convert server_list to list
      set_fact:
        server_list: [server_list]
      when: server_list is string
  tasks:
  - name: Install git
    package:
      name: git
      state: present

  - name: Download Ansible roles
    git:
      repo: https://github.com/ai4os/ai4-ansible
      dest: /opt/ai4-ansible
      version: fix_ssl_traefik
    
  - name: Add groups to Server node
    add_host:
      name: '{{ inventory_hostname  }}'
      groups:
      - consul_master
      - nomad_master
      - nomad_servers
      - consul_servers
      - consul
      - nomad

  - name: Enable Traefik
    add_host:
      name: '{{ inventory_hostname  }}'
      groups:
      - traefik_master
    when: launch_traefik

  - name: Add non used groups
    add_host:
      name: "none"
      groups:
      - nomad_cpu_clients
      - nomad_gpu_clients
      - nomad_clients
      - consul_clients

  - name: Create Ansible roles dir
    file:
      path: /etc/ansible/roles
      state: directory
      mode: 0755

  - name: Install Nomad role
    copy:
      src: /opt/ai4-ansible/roles/nomad/
      dest: /etc/ansible/roles/nomad
      mode: 0755
      remote_src: yes

  - name: Install Consul role
    copy:
      src: /opt/ai4-ansible/roles/consul/
      dest: /etc/ansible/roles/consul
      mode: 0755
      remote_src: yes

  - name: Include roles vars
    include_vars:
      file: /opt/ai4-ansible/group_vars/all.yml

  - name: Set facts
    set_fact:
      consul_public_ip: "{{ server_list[0] }}"
      my_ip: "{{ server_private_ip }}"
      username: cloudadm
      path: /opt/cloudadm/
      nomad_dc: ifca-ai4eosc
      domain: ifca
      nomad_namespaces:
        - ai4eosc
        - imagine
        - tutorials
      nomad_version: "{{ nomad_input_version }}"
      consul_version: "{{ consul_input_version }}"

  - name: Invoke consul role
    include_role:
      name: consul

  - name: Invoke nomad role
    include_role:
      name: nomad
