---
- hosts: localhost
  connection: local
  vars:
    server_list: "{{ nomad_server_list | default([ansible_default_ipv4.address]) }}"
    server_public_ip: "{{ IM_NODE_PUBLIC_IP | default(ansible_default_ipv4.address) }}"
    server_private_ip: "{{ IM_NODE_PRIVATE_IP | default(ansible_default_ipv4.address) }}"
  pre_tasks:
    - name: Convert server_list to list
      set_fact:
        server_list: [server_list]
      when: server_list is string
  roles:
    - role: 'grycap.consul'
      consul_server: true
      consul_dns: false
      consul_config_dir: /etc/consul
      consul_join_ips: "{{ server_list }}"
      consul_bootstrap_expect: "{{ server_list | length }}"
      consul_advertise_addr: "{{ server_private_ip }}"
      consul_policies:
        - name: nomad-client-policy
          description: Consul Nomad Client Policy
          rules: |
            agent_prefix "" {
              policy = "read"
            }
            node_prefix "" {
              policy = "read"
            }
            service_prefix "" {
              policy = "write"
            }
            key_prefix "" {
              policy = "read"
            }
        - name: nomad-server-policy
          description: Consul Nomad Server Policy
          rules: |
            agent_prefix "" {
              policy = "read"
            }
            node_prefix "" {
              policy = "read"
            }
            service_prefix "" {
              policy = "write"
            }
            acl = "write"
        - name: traefik-dashboard-server-policy
          description: Consul Traefik dashboard Policy
          rules: |
            key_prefix "traefik" {
              policy = "write"
            }
            service "traefik" {
              policy = "write"
            }
            agent_prefix "" {
              policy = "read"
            }
            node_prefix "" {
              policy = "read"
            }
            service_prefix "" {
              policy = "read"
            }
    - role: grycap.nomad
      nomad_name: "{{ ansible_hostname }}"
      server_enabled: true
      client_enabled: false
      use_tls: true
      tls_http: true
      tls_rpc: true
      generate_tls: true
      tls_public_ip: "{{ server_public_ip }}"
      tls_private_ip:  "{{ server_private_ip }}"
      bind_address: "0.0.0.0"
      use_consul: true
      consul_address: "127.0.0.1:8501"
      consul_ssl: true
      consul_verify_ssl: false
      consul_ca_file: "/etc/consul/certs/consul-agent-ca.pem"
      create_nomad_service: true
      consul_ACL_token_set: true
      consul_token: "{{ consul_tokens['nomad-server-policy'] }}"
      server_bootstrap_expect: "{{ server_list | length }}"
      acl_enabled: true
      acl_bootstrap: true
  tasks:
    - name: Create traefik job
      copy:
        content: |
          job "traefik" {
            region      = "global"
            datacenters = ["dc1"]
            type        = "service"
              constraint {
                attribute  = "${meta.public_ip}"
                value      = "yes"
              }
            group "traefik" {
              count = 1
              network {
                port "http" {
                  static = 80
                }
                port "https" {
                  static = 443
                }
                port "api" {
                  static = 8081
                }
              }
              service {
                name = "traefik"
                check {
                  name     = "alive"
                  type     = "tcp"
                  port     = "http"
                  interval = "10s"
                  timeout  = "2s"
                }
              }
              task "traefik" {
                driver = "docker"
                config {
                  image        = "traefik:v2.10"
                  network_mode = "host"
                  volumes = [
                    "local/traefik.toml:/etc/traefik/traefik.toml",
                  ]
                }
                template {
                  data = <<EOF
          [entryPoints]
              [entryPoints.http]
              address = ":80"
              [entryPoints.http]
              address = ":443"
              [entryPoints.traefik]
              address = ":8081"
          [api]
              dashboard = true
              insecure  = true
              debug = true
          # Enable Consul Catalog configuration backend.
          [providers.consulCatalog]
              prefix           = "traefik"
              exposedByDefault = false
          [providers.consulCatalog.endpoint]
              address = "127.0.0.1:8500"
              token = "{{ consul_tokens['traefik-dashboard-server-policy'] }}"
              scheme  = "http"
          EOF
                  destination = "local/traefik.toml"
                }
                resources {
                  cpu    = 100
                  memory = 128
                }
              }
            }
          }
        dest: /opt/nomad/traefik.hcl
        mode: 0644

    - name: Submit traefik job
      command: nomad job run -check-index 0 /opt/nomad/traefik.hcl